[package]
name = "ash-present-wrappers"
version = "0.1.0"
edition = "2021"

[dependencies]
ash-common-imports = {path = "../ash-common-imports"}
ash-sync-wrappers = {path = "../ash-sync-wrappers"}
ash-queue-wrappers = {path = "../ash-queue-wrappers"}
