[package]
name = "ash-data-wrappers"
version = "0.1.0"
edition = "2021"

[dependencies]
ash-context = {path = "../ash-context"}
ash-queue-wrappers = {path = "../ash-queue-wrappers"}
ash-sync-wrappers = {path = "../ash-sync-wrappers"}

