[package]
name = "ash-wrappers"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = {version = "0.38.0+1.3.281"}
ash-window = "0.13.0"
raw-window-handle = "0.6.2"
gpu-allocator = {git = "https://github.com/Traverse-Research/gpu-allocator.git", branch = "ash-0.38"}
image = "0.25.2"
