[package]
name = "game-logic"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.0"
render-manager = {path="../render-manager"}
input-aggregator = {path="../input-aggregator"}
physics = {path= "../physics" }