[package]
name = "render-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
ash-ad-wrappers = {path = "ash-ad-wrappers"}
renderables = {path = "renderables"}
renderers = {path = "renderers"}
crossbeam-channel = "0.5"
spin = "0.9.8"
