[package]
name = "render-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.0"
ash-ad-wrappers = {path = "ash-ad-wrappers"}
# triangle-mesh-renderer = {path = "triangle-mesh-renderer"}
